name: Unit Testing

on:
  pull_request:
    branches:
      - 'master'
      - 'development'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Lint
        run: |
          isort . --check
          black . --check
          #flake8 .
      - name: Security
        run: |
          bandit --severity-level medium -r ./
      - name: Unit Testing
        run: |
          pytest embedding_api/tests/
